### ISSUE TITLE
Q on dependencies

### ISSUE THREAD

**Issue by jiarong** [thackl/pro-tycheposons#1]
Hi, I was testing `element-finder/bin/irve_finder`. Most of dependencies can be installed by bioconda except `seq-len`, `gff2bed`, and `hmmer-tbl2tsv`. Any suggestion on how to install these? thanks!

**Comment by thackl** [comment]
Yes, they are part of my custom script collection https://github.com/thackl/seq-scripts. Those three scripts should run just out of the box

**Comment by jiarong** [comment]
Thanks!  I found one more (`tsv-select`), but it's not in the collection. How can I get this one?

**Comment by iimog** [comment]
This tool is part of https://ebay.github.io/tsv-utils/
