### ISSUE TITLE
interpreting the results

### ISSUE THREAD

**Issue by jiarong** [thackl/pro-tycheposons#3]
Hi, are genomic regions in the output `XYZ-elements.tsv` are good candidates for tycheposon? or some more screening is needed? thanks!

**Comment by thackl** [comment]
The table is an exhaustive list that needs further screening. There is, for example, a score column that captures a lot of the features. But it is also rather a naive score and there is a large gray area with good and bad hits mixed.

Good hits should have an integrase, be flanked by tRNAs, and have 2 or more other hallmark hits. You can get that roughly from a score >10. But, as I said, there is no really clear cutoff.

**Comment by jiarong** [comment]
I have follow up Q. I noticed there are many hits with integrase, flanked by tRNAs, and score at ~13, but only with 1 other hallmark gene (excluding integrase). What's your experience on these borderline cases? I am wondering what could these hits be if not tycheposon? so I can pay attention with manual curation. Thanks!
