### ISSUE TITLE
tyrosine recombinase sequences

### ISSUE THREAD

**Issue by jiarong** [thackl/pro-tycheposons#4]
Hi Thomas, I am thinking about accessing the novelty of my tycheposon candidates by comparing the ones found in this study. There is a tree in `YR-phylogeny` but I can not find the sequences. Could you provide them? Thanks.

**Comment by thackl** [comment]
I've added the sequence data to the folder. `yr-pro-nr40.faa` contains Tyrosine recombinases found in Prochlorococcus from the study. `yr-all-nr40.faa` contains Prochlorococcus YRs + all the other intergrases (Smyshlyaev et al., 2019 https://doi.org/10.1101/542381). `yr-all-nr40-einsi-gp80.afa` contains the trimmed alignment I used to compute the tree. Hope that helps!

**Comment by thackl** [comment]
Forgot to mention - the nr40 means that those sets are all redundancy-reduced, i.e. only diverse representative are in there.

**Comment by jiarong** [comment]
@thackl Do you have the subgroup info of sequences in `yr-all-nr40.faa` (the labels used in Fig 3A).
![image](https://user-images.githubusercontent.com/450253/141600203-5df55b89-7a39-49b0-907a-669054c566c6.png)

**Comment by thackl** [comment]
Sorry, I missed the notification, so not sure if still relevant. No, I don't have those in a useful form. I annotated them manually in the tree (comparing sequences to hmm profiles).
